### ISSUE TITLE
Download version

### ISSUE THREAD

**Issue by hnzlmnn** [jryannel/qt5-cadaques#204]
back-link: index.html#a-book-about-qt5

Hey there, even if the book isn't finished, a download the current book option would be awsome.

**Comment by jryannel** [comment]
Hi, 
What is the reason to have a download book? Is the HTML version not readable? Can we fix it? We just discuss if we should break the chapters into smaller pages. So there would be a chapter landing page and then smaller pages for each section, so that users do not need to scroll so much. Would this help? Or how about a better search integration?
Anyway we also think about a download version, but we would like to fix the html version to:-)

**Comment by hnzlmnn** [comment]
Thanks for your quick reply,
I just think it's easier to read on the go if you have a PDF or epub file.
This could be easily created. The main reason for me to ask was, because I
wanted an offline version to be able to read on the train.
Am 08.01.2014 07:40 schrieb "jryannel" notifications@github.com:

**Comment by jryannel** [comment]
A download version will come this month. PDF and ePub.

**Comment by hnzlmnn** [comment]
Perfect!
Am 08.01.2014 07:52 schrieb "jryannel" notifications@github.com:
